# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/videostream.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pp/proto/videostream.proto\x12\x0bvideostream\"b\n\nVideoFrame\x12\x0f\n\x07y_plane\x18\x01 \x01(\x0c\x12\x0f\n\x07u_plane\x18\x02 \x01(\x0c\x12\x0f\n\x07v_plane\x18\x03 \x01(\x0c\x12\x0f\n\x07y_width\x18\x04 \x01(\x05\x12\x10\n\x08y_height\x18\x05 \x01(\x05\"b\n\x0cStreamStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x30\n\ndetections\x18\x03 \x03(\x0b\x32\x1c.videostream.DetectionResult\"E\n\x0f\x44\x65tectionResult\x12\r\n\x05label\x18\x01 \x01(\t\x12\x11\n\tdirection\x18\x02 \x01(\t\x12\x10\n\x08\x64istance\x18\x03 \x01(\t\"=\n\x0cSetupRequest\x12\x15\n\ruser_question\x18\x01 \x01(\t\x12\x16\n\x0e\x66ilter_objects\x18\x02 \x01(\x08\"L\n\rSetupResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x11objects_to_detect\x18\x03 \x03(\t2V\n\rVideoStreamer\x12\x45\n\x0bStreamVideo\x12\x17.videostream.VideoFrame\x1a\x19.videostream.StreamStatus(\x01\x30\x01\x32_\n\x14\x43onfigurationService\x12G\n\x0eSetupDetection\x12\x19.videostream.SetupRequest\x1a\x1a.videostream.SetupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.videostream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFRAME']._serialized_start=44
  _globals['_VIDEOFRAME']._serialized_end=142
  _globals['_STREAMSTATUS']._serialized_start=144
  _globals['_STREAMSTATUS']._serialized_end=242
  _globals['_DETECTIONRESULT']._serialized_start=244
  _globals['_DETECTIONRESULT']._serialized_end=313
  _globals['_SETUPREQUEST']._serialized_start=315
  _globals['_SETUPREQUEST']._serialized_end=376
  _globals['_SETUPRESPONSE']._serialized_start=378
  _globals['_SETUPRESPONSE']._serialized_end=454
  _globals['_VIDEOSTREAMER']._serialized_start=456
  _globals['_VIDEOSTREAMER']._serialized_end=542
  _globals['_CONFIGURATIONSERVICE']._serialized_start=544
  _globals['_CONFIGURATIONSERVICE']._serialized_end=639
# @@protoc_insertion_point(module_scope)
