# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import videostream_pb2 as app_dot_proto_dot_videostream__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/proto/videostream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class VideoStreamerStub(object):
    """Service definition for streaming video frames and receiving stream statuses
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVideo = channel.stream_stream(
                '/videostream.VideoStreamer/StreamVideo',
                request_serializer=app_dot_proto_dot_videostream__pb2.VideoFrame.SerializeToString,
                response_deserializer=app_dot_proto_dot_videostream__pb2.StreamStatus.FromString,
                _registered_method=True)


class VideoStreamerServicer(object):
    """Service definition for streaming video frames and receiving stream statuses
    """

    def StreamVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=app_dot_proto_dot_videostream__pb2.VideoFrame.FromString,
                    response_serializer=app_dot_proto_dot_videostream__pb2.StreamStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'videostream.VideoStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('videostream.VideoStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoStreamer(object):
    """Service definition for streaming video frames and receiving stream statuses
    """

    @staticmethod
    def StreamVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/videostream.VideoStreamer/StreamVideo',
            app_dot_proto_dot_videostream__pb2.VideoFrame.SerializeToString,
            app_dot_proto_dot_videostream__pb2.StreamStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConfigurationServiceStub(object):
    """Service definition for setting up the detection configuration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetupDetection = channel.unary_unary(
                '/videostream.ConfigurationService/SetupDetection',
                request_serializer=app_dot_proto_dot_videostream__pb2.SetupRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_videostream__pb2.SetupResponse.FromString,
                _registered_method=True)


class ConfigurationServiceServicer(object):
    """Service definition for setting up the detection configuration
    """

    def SetupDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigurationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetupDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupDetection,
                    request_deserializer=app_dot_proto_dot_videostream__pb2.SetupRequest.FromString,
                    response_serializer=app_dot_proto_dot_videostream__pb2.SetupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'videostream.ConfigurationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('videostream.ConfigurationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigurationService(object):
    """Service definition for setting up the detection configuration
    """

    @staticmethod
    def SetupDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/videostream.ConfigurationService/SetupDetection',
            app_dot_proto_dot_videostream__pb2.SetupRequest.SerializeToString,
            app_dot_proto_dot_videostream__pb2.SetupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
